// insert your code here

/*
ALGORITMA
1.BUKA TUTUPNYA DULU
2.TOTAL PAKAIAN ADA 20
3.AMBIL PAKAIAN 1
4.MASUKAN PAKAIAN KE MESIN CUCI
5.ULANGI MEMASUKAN PAKAIAN SAMPAI 20
6.TUTUP PENUTUP MESIN CUCI
7.TOMBOL POWER AKAN MENYALA JIKA SEMUA PAKAIAN MASUK KEMESIN CUCI

PSEUCODE
STORE total AS NUMBER WITH 20

FOR i FROM 0 TO total INCREMENT BY 1
    DISPLAY 'TOMBOL POWER MENYALA'
END FOR